### PR TITLE
fix: state not found for a document where it should be findable

### LINKED ISSUE #147: State not found for a document where it should be findable.
Note that idnits2 at https://author-tools.ietf.org/api/idnits?url=https://www.ietf.org/archive/id/draft-ietf-spring-cs-sr-policy-06.txt reports no issues

idnits3 as of afb8ea0 reports:

43  Warning
 └- Code - UNDEFINED_STATE
 └- Desc - The draft reference I-D.draft-bashandy-rtgwg-segment-routing-uloop does not have a defined state or could not be fetched.
 └- Ref  - https://datatracker.ietf.org/doc/I-D.draft-bashandy-rtgwg-segment-routing-uloop

The ref is odd - that URL would never resolve. 
https://datatracker.ietf.org/doc/draft-bashandy-rtgwg-segment-routing-uloop/ does.
Where is idnits3 _looking_ for the state of the document and not finding it?

### PR DESCRIPTION
**Pull request by Dmutre**
closes #147

### CODE REVIEW

File: lib/modules/downref.mjs [hunk 1]
```diff
@@ -163,7 +163,9 @@ function normalizeDraftReferences (references) {
   return references
     .map((ref) => {
       let normalized = ref.replace(/^\[|\]$/g, '')
-      normalized = normalized.replace(/-\d{2}$/, '')
+      normalized = normalized
+        .replace(/-\d{2}$/, '')
```
Comment (rjsparks) [inline lib/modules/downref.mjs:257]: If this code ever encounters a reference to document without its version number (which is a common thing for _other_ software here to have to do - it means "go find the current version of the draft with this name") it will fail.

Consider draft-ietf-tsvwg-ieee-802-11-11.txt: The unversioned reference would be to `I-D.ietf-tsvwg-ieee-802-11`. This code would then try to look up `ietf-tsvwg-ieee-802` and fail (the correct lookup would be for `draft-ietf-tsvwg-ieee-802-11`).

I need to review more and search for examples before approving this or requesting changes

**Comment by rjsparks** [comment]
After some digging, I'm now sure that this PR is not solving the right problem for text documents.

The strings you are normalizing from the references are the wrong strings to try to use to look things up.
For instance, at this reference (there are many like it in the txt form of the document mentioned in #147):
```
	   [I-D.ietf-pce-multipath]
	              Koldychev, M., Sivabalan, S., Saad, T., Beeram, V. P.,
	              Bidgoli, H., Yadav, B., Peng, S., and G. S. Mishra, "PCEP
	              Extensions for Signaling Multipath Information", Work in
	              Progress, Internet-Draft, draft-ietf-pce-multipath-13, 9
	              April 2025, <https://datatracker.ietf.org/doc/html/draft-
	              ietf-pce-multipath-13>.
```
You should be seeing that the reference is to draft-ietf-pce-multipath-13, from the _link_ in the reference not from the bits between the [ and the ]. Some other document could have written this as
```
	   [multipath]
	              Koldychev, M., Sivabalan, S., Saad, T., Beeram, V. P.,
	              Bidgoli, H., Yadav, B., Peng, S., and G. S. Mishra, "PCEP
	              Extensions for Signaling Multipath Information", Work in
	              Progress, Internet-Draft, draft-ietf-pce-multipath-13, 9
	              April 2025, <https://datatracker.ietf.org/doc/html/draft-
	              ietf-pce-multipath-13>.
```
or have used any other arbitrary set of characters for the anchor text (e.g. [thatotherdraft] or, more frequently numeric anchors like [2]).

The problem for xml documents may be different. In the submitted XML for this doc, the reference looks like:
```
        <reference anchor="I-D.ietf-pce-multipath">
          <front>
            <title>PCEP Extensions for Signaling Multipath Information</title>
            <author fullname="Mike Koldychev" initials="M." surname="Koldychev">
              <organization>Ciena Corporation</organization>
            </author>
            <author fullname="Siva Sivabalan" initials="S." surname="Sivabalan">
              <organization>Ciena Corporation</organization>
            </author>
            <author fullname="Tarek Saad" initials="T." surname="Saad">
              <organization>Cisco Systems</organization>
            </author>
            <author fullname="Vishnu Pavan Beeram" initials="V. P." surname="Beeram">
              <organization>Juniper Networks, Inc.</organization>
            </author>
            <author fullname="Hooman Bidgoli" initials="H." surname="Bidgoli">
              <organization>Nokia</organization>
            </author>
            <author fullname="Bhupendra Yadav" initials="B." surname="Yadav">
              <organization>Ciena</organization>
            </author>
            <author fullname="Shuping Peng" initials="S." surname="Peng">
              <organization>Huawei Technologies</organization>
            </author>
            <author fullname="Gyan Mishra" initials="G. S." surname="Mishra">
              <organization>Verizon Inc.</organization>
            </author>
            <date day="9" month="April" year="2025"/>
            <abstract>
              <t>   Certain traffic engineering path computation problems require
   solutions that consist of multiple traffic paths, that together form
   a solution.  Returning just one single traffic path does not provide
   a valid solution.  This document defines mechanisms to encode
   multiple paths for a single set of objectives and constraints.  This
   allows encoding of multiple Segment Lists per Candidate Path within a
   Segment Routing Policy.  The new PCEP mechanisms are meant to be
   generic, where possible, to allow for future re-use outside of SR
   Policy.  The new PCEP mechanisms are applicable to both stateless and
   stateful PCEP.

              </t>
            </abstract>
          </front>
          <seriesInfo name="Internet-Draft" value="draft-ietf-pce-multipath-13"/
>
        </reference>
```
And the code should be pulling that `seriesInfo` tag `value` attribute to figure out what version of the draft is being referenced.

**Review by rjsparks — CHANGES_REQUESTED** [review]
A different approach is needed see the comments on the PR discussion.

**Review by rjsparks — CHANGES_REQUESTED** [review]
This continues to confuse two things:

* the handle inside the document to point to a reference in the reference section : such as `[I-D.draft-ietf-rtgwg-segment-routing-ti-lfa]`

and

* the document the reference in the reference section points to : such as `draft-ietf-rtgwg-segment-routing-ti-lfa-21`

The change in 9599889 figured out what document for which to check the state, but broke the check for whether the _handle_ was used inside the document text. At that commit, idnits3 produces 
```
 3  Warning
 └- Code - REFERENCE_NOT_USED
 └- Desc - The reference RFC draft-ietf-rtgwg-segment-routing-ti-lfa-21 is listed in the References section but is not mentioned in the document text.
 └- Ref  - https://authors.ietf.org/en/required-content#references
```
when run against https://www.ietf.org/archive/id/draft-ietf-spring-cs-sr-policy-06.txt

File: lib/modules/downref.mjs [hunk 2]
```diff
@@ -174,6 +182,67 @@ export async function validateDownrefs (doc, { mode = MODES.NORMAL } = {}) {
...
+    }
+
+    return acc;
+  }, { drafts: new Set(), rfcs: new Set() });
+
+  const draftList = normalizeDraftReferences(Array.from(drafts));
+  const rfcList   = Array.from(rfcs);
+
+  return [...draftList, ...rfcList]
+}
```
Comment (NGPixel) [inline lib/modules/downref.mjs]: Code styling: remove semi-colons

File: lib/parsers/txt.mjs [hunk 3]
```diff
@@ -803,6 +794,12 @@ export async function parse (rawText, filename) {
     }
 
     data.markers = markers
+
+    // Extracting draft references from reference section
+    const refLines = data.content.references
+    const draftsBySub = extractDraftsBySubsection(refLines)
+    data.extractedElements.draftStatusReferences.push(...draftsBySub);
```
Comment (NGPixel) [inline lib/parsers/txt.mjs]: Code styling: remove semi-colons

**Review by NGPixel — CHANGES_REQUESTED** [review]

**Review by rjsparks — DISMISSED** [review]
Please fix Nick's coding style issues.

**Review by NGPixel — DISMISSED** [review]
