### PR TITLE
fix: improved fqdn regexp, added restrictions just like in idnits2

### LINKED ISSUE #88: Restrict fqdn checks to an explicit list of TLDs
Carrying this forward out of #75:

Restrict matches the way idnits2 does at https://github.com/ietf-tools/idnits/blob/989e178a543d9e53d00740829260e24d8d25a10e/idnits#L2729-L2734

### PR DESCRIPTION
**Pull request by Dmutre**
closes #88, #138

### CODE REVIEW

File: lib/parsers/txt.mjs [hunk 1]
```diff
@@ -565,7 +565,9 @@ export async function parse (rawText, filename) {
       // FQRN Domain extraction
```
Comment (rjsparks) [inline lib/parsers/txt.mjs]: nit: FQDN

**Review by rjsparks — APPROVED** [review]

**Review by rjsparks — CHANGES_REQUESTED** [review]
Revoking the approval from a moment ago - I don't think things are right yet and wonder if there's been a negation somewhere in the reading of the logic of idnits2.

On this branch, for draft-ietf-spring-cs-sr-policy-06.txt, I still see _many_ complaints from idnits3 about, e.g.,

```
 2  Warning
 └- Code - INVALID_DOMAIN_TLD
 └- Desc - Domain "h.encaps" has an invalid TLD.
 └- Ref  - https://www.iana.org/domains/root/db

 3  Warning
 └- Code - INVALID_DOMAIN_TLD
 └- Desc - Domain "daniel.voyer" has an invalid TLD.
 └- Ref  - https://www.iana.org/domains/root/db
```

**Review by NGPixel — APPROVED** [review]
